/*
 * This source file was generated by the Gradle 'init' task
 */
package com.patrones;

import com.patrones.factory.AbstractFactory;
import com.patrones.implementation.BridgeMessageEncryption;
import com.patrones.implementation.IMessage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        IMessage bridge = new BridgeMessageEncryption(
                new AbstractFactory().getFactory().getEncryptService());

        String message = "Holis";
        String psw = "password";

        try {
            String result = bridge.encryptMessage(message, psw);
            System.out.println(result);
            System.out.println(bridge.getMethodClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
